kaliber-node now retrieves the icu data itself

diff --git a/library/bin/kaliber-node b/library/bin/kaliber-node
--- a/library/bin/kaliber-node
+++ b/library/bin/kaliber-node
@@ -1,2 +1,20 @@
 #!/bin/sh +x
-exec node --icu-data-dir="$( node -e 'process.stdout.write(require(`path`).dirname(require.resolve(`full-icu`)))' )" "$1" "$@"
+
+package="$( node -e 'process.stdout.write(require(`full-icu`).icupkg)' )"
+file="$( node -e 'process.stdout.write(require(`full-icu`).icudat)' )"
+dir="./icu-data"
+fileLocation="$dir/$file"
+
+mkdir -p "$dir"
+
+if test ! -f "$fileLocation"; then
+  echo "Downloading icu data package"
+  npm view "$package" dist.tarball | xargs curl | tar -xz --directory="$dir" --strip-components 1
+fi
+
+if test ! -f "$fileLocation"; then
+  echo "$fileLocation not found"
+  exit 1
+fi
+
+exec node --icu-data-dir="$dir" "$1" "$@"
